r_1 = int(input("enter the real part of first number"))
i_1 = int(input("enter the imaginary part of first number"))
r_2 = int(input("enter the real part of second number"))
i_2 = int(input("enter the imaginary part of second number"))
no1 = complex(r_1,i_1)
no2 = complex(r_2,i_2)
print("sum of two numbers is:"+str(no1+no2))
print("difference between the two numbers is:"+str(abs(no1-no2)))
print("multiplication of two numbers is:"+str(no1*no2))
print("division of two numbers is:"+str(no2/no1))
